#!/bin/bash

while getopts p:b:u:m:i:t:r: option
do
    case "${option}"
    in
        p) export PRODUCT="${OPTARG}";;
        b) export BOARD="${OPTARG}";;
        u) export BUNDLE="${OPTARG}";;
        m) export FX_METRICS="${OPTARG}";;
        i) export DISK_IMG="${OPTARG}";;
        t) export TARGET_DEVICE="${OPTARG}";;
        r) export FUCHSIA_ROOT="${OPTARG}";;
    esac
done


jiri_init (){
    export PATH="${FUCHSIA_ROOT:-$PWD}/.jiri_root/bin":$PATH
    jiri init -analytics-opt=false "${FUCHSIA_ROOT:-$PWD}"
    jiri import -name=integration flower https://fuchsia.googlesource.com/integration
}

update (){
    if [[ ! -f "${FUCHSIA_ROOT:-$PWD}/.config/chrome_infra/auth/creds.json" ]]; then
        cipd auth-login
    fi

    jiri update
}

prebuild (){
    if [[ "${PREBUILD:-false}" == true ]]; then
        fx --dir out/"${NAME:-"${PRODUCT:-workbench_eng}"}" set "${PRODUCT:-workbench_eng}"."${BOARD:-x64}" --ccache --args=is_debug="${DEBUG:-false}"
    fi
}

build (){
    if fx metrics "${FX_METRICS:-disable}"; then
        fx build -j 0 --log "build.log.$(date +'%Y%m%d%h%m')$((1 + $RANDOM % 99))"
    else
        update
        build
    fi
}

flash_zedboot (){
    # Try to create a loop device, if allowed (/dev/fuchsia by default)
    if [[ -f "${DISK_IMG:-/fuchsia/disk.img}" ]]; then
        if mknod -m 0660 /dev/fuchsia b 7 8 &> /dev/null; then
            if losetup /dev/fuchsia "${DISK_IMG}" &> /dev/null; then
                TARGET_DEVICE=/dev/fuchsia
            fi
        else
            TARGET_DEVICE="${DISK_IMG:-/fuchsia/disk.img}"
        fi
    fi

    if [[ -f "${TARGET_DEVICE}" ]]; then
        fx mkzedboot -f "${TARGET_DEVICE}"
    fi
}

flash_installer (){
    if [[ -f "${TARGET_DEVICE}" ]]; then
        fx mkinstaller -f "${TARGET_DEVICE}"
    fi
}

deploy (){
    pause "Please boot the target device in order to update it over the network, then press a key to continue."
    fx pave
}

femu (){
    if ! fx vdl start --host-gpu -N -u "${FUCHSIA_ROOT:-$PWD}/scripts/start-unsecure-internet.sh"; then
        femu-headless
    fi
}

femu-headless (){
    fx vdl start --headless
}

# First, initialize
jiri_init
"${FUCHSIA_ROOT:-$PWD}/tools/ssh-keys/gen-ssh-keys.sh"

case $1 in
    update)
        update
    ;;

    build)
        prebuild
        build
    ;;

    flash|mkzedboot)
        flash_zedboot
        deploy
    ;;

    flash_installer|mkinstaller)
        flash_installer
    ;;

    femu)
        femu
    ;;

    femu-headless)
        femu-headless
    ;;

    help|'')
        echo -e "\e[1mUsage\e[0m\n" \
                "\e[1mInteractive shell:\e[0m   docker run -it --user 1000:1000 -v <host-side dir>:/fuchsia amitie10g/google-fuchsia-jiri bash\n"

        echo -e "\e[1mBuilding\e[0m\n" \
                "\e[1mDownload/update:\e[0m     docker run --user 1000:1000 -v <fuchsia source tree>:/fuchsia amitie10g/google-fuchsia-jiri update\n" \
                "\e[1mBuild:\e[0m               docker run --user 1000:1000 -v <fuchsia source tree>:/fuchsia amitie10g/google-fuchsia-jiri build\n\n" \
                "Before downloading, be sure to expose the volume to the right host-side location.\n"

        echo -e "\e[1mFlashing\e[0m\n" \
                "\e[1mFlash zedboot:\e[0m           docker run --privileged --user 1000:1000 -v <fuchsia source tree>:/fuchsia amitie10g/google-fuchsia-jiri mkzedboot\n" \
                "\e[1mFlash installer:\e[0m     docker run --privileged --user 1000:1000 -v <fuchsia source tree>:/fuchsia amitie10g/google-fuchsia-jiri mkinstaller\n\n" \
                "Before installing into a device, be sure to have it exposed it to the container;\n" \
                "otherwise, you may use a disk image at the host-side, or use a physical USB drive.\n" \
                "mkinstaller only works with a physical USB drive as target; using other block devices will fail.\n"


        echo -e "\e[1mTo create an 8 GB zero-filled file as following:\e[0m\n" \
                "\e[1mIn Windows:\e[0m  fsutil file createnew disk.img 8589934592\n" \
                "\e[1mIn Linux:\e[0m    dd if=/dev/zero of=disk.img bs=4096 count=2097152\n\n" \
                "Then, you may clone the disk image into your USB drive.\n"

        echo -e "It is highly recommended to run in privileged mode (\e[1m--privileged\e[0m) in order to access your block devices properly;"
        echo -e "otherwise, run at the host side (once \$PATH is set properly).\n"

        echo -e "Visit \e[1mhttps://fuchsia.dev/fuchsia-src/get-started\e[0m for more information."
    ;;

    shell|bash)
        bash -c 'bash --rcfile /etc/skel/.bashrc'
    ;;

    *)
        $1
    ;;
esac
