name: Docker Image CI

on:
  push:
    branches: [ "base" ]
  pull_request:
    branches: [ "base" ]
  schedule: 
   - cron: '0 0 1 */3 *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build the Docker image
      run: docker buildx build --platform linux/amd64 -t ${{ secrets.DOCKERHUB_USERNAME }}/google-fuchsia-jiri --push .
